services:
  app:
    image: mcr.microsoft.com/vscode/devcontainers/base:bookworm
    command: sleep infinity
    environment:
      - ENV=devcontainer
    working_dir: '/workspace/api'
    volumes:
      - ..:/workspace

  api:
    build:
      context: ../api
      dockerfile: ../api/Dockerfile.dev
    volumes:
      - ../api:/app
    ports:
      - 80:80
    tty: true
    env_file: ../api/.env.dev
    command: >
      ash -c "go run main.go"
    depends_on:
      mysql:
        condition: service_healthy

  test-api:
    build:
      context: ../api
      dockerfile: ../api/Dockerfile.dev
    volumes:
      - ../api:/app
    ports:
      - 88:80
    tty: true
    command: >
      ash -c "go run main.go"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0.28
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=template
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=password
      - TZ=Asia/Tokyo
    volumes:
      - ../api/mysql/mysql-data:/var/lib/mysql
      - ../api/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ../api/mysql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/x86_64
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=docker
      - PMA_PASSWORD=password
    ports:
      - 4040:80
    depends_on:
      mysql:
        condition: service_healthy

  minio:
    image: minio/minio:RELEASE.2024-07-29T22-14-52Z
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --address :9000 --console-address :9001
    volumes:
      - ../api/minio/data:/data

  mc:
    image: minio/mc:RELEASE.2023-12-23T08-47-21Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 root minio123;
      mc mb myminio/sample;
      "
